
# tap repositories and their packages

tap homebrew/core
brew ada-url
brew ansible
brew bash
brew bat
brew brotli
brew btop
brew c-ares
brew ca-certificates
brew certifi
brew cffi
brew cryptography
brew fastfetch
brew fd
brew fmt
brew fzf
brew gettext
brew gnu-getopt
brew hdrhistogram_c
brew icu4c@78
brew json-c
brew libffi
brew libgit2
brew libnghttp2
brew libnghttp3
brew libngtcp2
brew libsodium
brew libssh
brew libssh2
brew libunistring
brew libuv
brew libyaml
brew llhttp
brew lpeg
brew lua
brew luajit
brew luv
brew lz4
brew merve
brew mpdecimal
brew nbytes
brew ncurses
brew neovim
brew node
brew oniguruma
brew openssl@3
brew pcre2
brew podman
brew podman-compose
brew pycparser
brew python@3.14
brew readline
brew ripgrep
brew simdjson
brew simdutf
brew sqlite
brew starship
brew stow
brew trash-cli
brew tree
brew tree-sitter
brew unibilium
brew utf8proc
brew uvwasi
brew xz
brew yazi
brew yyjson
brew zoxide
brew zsh-autosuggestions
brew zsh-syntax-highlighting
brew zstd

tap homebrew/cask
cask font-jetbrains-mono-nerd-font
cask ghostty

tap asmvik/formulae

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836 GarageBand (10.4.13)
appstore 408981434 iMovie (10.4.4)
appstore 361285480 Keynote Creator Studio (15.1.1)
appstore 985367838 Microsoft Outlook (16.111.1)
appstore 361304891 Numbers Creator Studio (15.1)
appstore 361309726 Pages Creator Studio (15.1.1)
appstore 497799835 Xcode (26.6)
