splash = false
ipc = true
preload = /home/kivanc57/.config/backgrounds/retrowave-2560x1440-pyramid-neon-colors-80s-nostalgia-27185.jpg
wallpaper = ,/home/kivanc57/.config/backgrounds/retrowave-2560x1440-pyramid-neon-colors-80s-nostalgia-27185.jpg
