splash = false
ipc = true
preload = /home/kivanc57/.config/backgrounds/retro-vibe-2560x1440-spectrum-colors-abstract-art-27158.jpg
wallpaper = ,/home/kivanc57/.config/backgrounds/retro-vibe-2560x1440-spectrum-colors-abstract-art-27158.jpg
